### PR TITLE
Prepare for release: Update version 1.1.1 -> 1.1.2

### PR DESCRIPTION
**Pull request by H-Shay**

### CODE REVIEW

**Review by DMRobertson — APPROVED** [review]

**Comment by clokep** [comment]
The test failure seems real? It is complaining about using something which is not exported, which for the module API seems bad.

**Comment by clokep** [comment]
We should probably update the readme for the minimum version of Synapse this supports?

**Comment by H-Shay** [comment]
> We should probably update the readme for the minimum version of Synapse this supports?

Good point I hadn't thought of that - although the code will run fine on older versions of Synapse, you'll just get the weird mypy failure is you run the lints. Is it worth mentioning that?

**Comment by H-Shay** [comment]
I've bumped the compatible version in the `readme` and `setup.cfg`, predictably everything fails now as synapse v1.84.0 is not available until tuesday - I am assuming I should just leave this on ice until then.

**Comment by clokep** [comment]
@H-Shay I think you checked your virtualenv in.

**Comment by H-Shay** [comment]
Fixed it, thank you for pointing it out.

**Comment by H-Shay** [comment]
The CI is now green on this, any objections to me merging and releasing?

**Comment by H-Shay** [comment]
Merged #16 into main.

**Pull request merged**
